import { format } from 'date-fns'
import { Brain, AlertTriangle, CheckCircle, Clock } from 'lucide-react'

interface AiReport {
  id: string
  summary: string
  riskLevel: string
  findings: string
  recommendations: string
  doctorNotes?: string
  status: string
  createdAt: string
}

const riskConfig: Record<string, { color: string; bg: string; border: string; icon: typeof AlertTriangle }> = {
  HIGH: { color: 'text-red-700', bg: 'bg-red-50', border: 'border-red-200', icon: AlertTriangle },
  MEDIUM: { color: 'text-amber-700', bg: 'bg-amber-50', border: 'border-amber-200', icon: AlertTriangle },
  LOW: { color: 'text-green-700', bg: 'bg-green-50', border: 'border-green-200', icon: CheckCircle },
  UNKNOWN: { color: 'text-slate-700', bg: 'bg-slate-50', border: 'border-slate-200', icon: Clock },
}

export function AiReportTab({ reports }: { reports: AiReport[] }) {
  if (!reports || reports.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center py-20 text-center animate-slide-up">
        <div className="w-16 h-16 rounded-2xl bg-blue-50 flex items-center justify-center mb-4">
          <Brain className="w-8 h-8 text-blue-300" />
        </div>
        <p className="text-slate-600 font-medium">No AI report available yet</p>
        <p className="text-sm text-slate-400 mt-1">Upload your medical documents to generate an AI analysis</p>
      </div>
    )
  }

  return (
    <div className="space-y-6 animate-slide-up">
      <div className="flex items-start gap-3 p-4 bg-blue-50 border border-blue-100 rounded-xl">
        <Brain className="w-5 h-5 text-blue-600 mt-0.5 shrink-0" />
        <div>
          <p className="text-sm font-semibold text-blue-800">AI-Assisted Preliminary Analysis</p>
          <p className="text-xs text-blue-600 mt-0.5">This report is generated by AI to assist your doctor. It is not a medical diagnosis. Always consult with your assigned physician.</p>
        </div>
      </div>

      {reports.map((report) => {
        const risk = riskConfig[report.riskLevel] || riskConfig.UNKNOWN
        const RiskIcon = risk.icon
        return (
          <div key={report.id} className="bg-white rounded-2xl border border-slate-100 shadow-sm overflow-hidden">
            {/* Header */}
            <div className={`flex items-center justify-between p-5 ${risk.bg} border-b ${risk.border}`}>
              <div className="flex items-center gap-3">
                <RiskIcon className={`w-5 h-5 ${risk.color}`} />
                <div>
                  <p className={`text-sm font-bold ${risk.color}`}>{report.riskLevel} RISK ASSESSMENT</p>
                  <p className="text-xs text-slate-500 mt-0.5">Generated {format(new Date(report.createdAt), 'MMMM d, yyyy')}</p>
                </div>
              </div>
              <span className={`status-badge ${risk.bg} ${risk.color} border ${risk.border}`}>{report.status}</span>
            </div>

            <div className="p-6 space-y-6">
              {/* Summary */}
              <div>
                <h3 className="text-xs font-semibold text-slate-500 uppercase tracking-wider mb-2">Executive Summary</h3>
                <p className="text-sm text-slate-700 leading-relaxed">{report.summary}</p>
              </div>

              {/* Findings */}
              <div>
                <h3 className="text-xs font-semibold text-slate-500 uppercase tracking-wider mb-2">Key Findings</h3>
                <div className="bg-slate-50 rounded-xl p-4">
                  <p className="text-sm text-slate-700 leading-relaxed whitespace-pre-line">{report.findings}</p>
                </div>
              </div>

              {/* Recommendations */}
              <div>
                <h3 className="text-xs font-semibold text-slate-500 uppercase tracking-wider mb-2">AI Recommendations</h3>
                <div className="bg-blue-50 rounded-xl p-4 border border-blue-100">
                  <p className="text-sm text-blue-800 leading-relaxed whitespace-pre-line">{report.recommendations}</p>
                </div>
              </div>

              {/* Doctor Notes */}
              {report.doctorNotes && (
                <div>
                  <h3 className="text-xs font-semibold text-slate-500 uppercase tracking-wider mb-2">Doctor&apos;s Notes</h3>
                  <div className="bg-green-50 rounded-xl p-4 border border-green-100">
                    <p className="text-sm text-green-800 leading-relaxed">{report.doctorNotes}</p>
                  </div>
                </div>
              )}
            </div>
          </div>
        )
      })}
    </div>
  )
}
